### ISSUE TITLE
Problema con el Modulo en Odoo 12

### ISSUE THREAD

**Issue by smedi08** [Comunitea/external_modules#35]
Buenas tardes, he probado vuestro modulo y me encuentro con el siguiente error, iniciar una nueva sesión:

Uncaught TypeError: Cannot read property 'find' of undefined
https://tienda.distribucionesdogcat.com/web/content/148399-ab4c92a/web.assets_common.js:3675
Rastreo de error:
TypeError: Cannot read property 'find' of undefined
    at Class.$ (https://tienda.distribucionesdogcat.com/web/content/148399-ab4c92a/web.assets_common.js:3675:17)
    at Class.loading_message (https://tienda.distribucionesdogcat.com/web/content/296279-dd45a0a/telesale.assets.js:187:1083)
    at child.fetch (https://tienda.distribucionesdogcat.com/web/content/296279-dd45a0a/telesale.assets.js:52:1174)
    at child.load_server_data (https://tienda.distribucionesdogcat.com/web/content/296279-dd45a0a/telesale.assets.js:52:2024)
    at child.initialize (https://tienda.distribucionesdogcat.com/web/content/296279-dd45a0a/telesale.assets.js:52:968)
    at child.Backbone.Model (https://tienda.distribucionesdogcat.com/web/content/296330-5591c40/web.assets_backend.js:40:1299)
    at new child (https://tienda.distribucionesdogcat.com/web/content/296330-5591c40/web.assets_backend.js:82:455)
    at Class.init (https://tienda.distribucionesdogcat.com/web/content/296279-dd45a0a/telesale.assets.js:179:972)
    at Class.prototype.<computed> [as init] (https://tienda.distribucionesdogcat.com/web/content/148399-ab4c92a/web.assets_common.js:3537:488)
    at new Class (https://tienda.distribucionesdogcat.com/web/content/148399-ab4c92a/web.assets_common.js:3538:65)

**Comment by omar7r** [comment]
Hola,

No está todavía migrado a la versión 12.0, sólo se creó la rama para comenzar la migración, espero que para la semana que viene sea funcional.
